### ISSUE TITLE
Rejected (Outdated miner)

### ISSUE THREAD

**Issue by olinitesh** [JK-Rolling/DuinoCoinI2C_RPI#13] opened 2022-02-01 04:14 UTC
Unable to get any accepted one. It just says Rejected(Outdated miner). Is it due to server issues or anything else? Internet works fine. Ping works fine.

**Comment by Hive89** [comment] 2022-02-01 06:54
Hi, I have the same problem since about 5-6h

**Comment by JMPP2** [comment] 2022-02-01 07:46
Hi, I have the same problem

**Comment by Hive89** [comment] 2022-02-02 06:56
problem has been fixed, see :https://github.com/ricaun/DuinoCoinI2C/issues/77

**Comment by JK-Rolling** [comment] 2022-02-06 09:45
this is server side issue. root caused to version regex. closing as nothing to do from my side

**Closed as completed by JK-Rolling** 2022-02-06 09:45 UTC
